# Generated by Django 2.0.3 on 2018-04-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('sender', models.EmailField(max_length=254)),
                ('cc_myself', models.BooleanField()),
            ],
        ),
    ]
