# Generated by Django 2.0.3 on 2018-04-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedemo', '0002_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
