# Generated by Django 2.0.3 on 2018-04-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180404_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuFacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=20)),
                ('manufacturing_date', models.DateField()),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cellarea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cell_technology', models.CharField(max_length=20)),
                ('num_of_cells', models.IntegerField()),
                ('num_of_cells_in_series', models.IntegerField()),
                ('num_of_series_strings', models.IntegerField()),
                ('num_of_diodes', models.IntegerField()),
                ('series_fuse_rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interconnect_material', models.CharField(max_length=20)),
                ('interconnect_supplier', models.CharField(max_length=20)),
                ('superstrate_type', models.CharField(max_length=20)),
                ('superstrate_manufacturer', models.CharField(max_length=20)),
                ('substrate_type', models.CharField(max_length=20)),
                ('substrate_manufacturer', models.CharField(max_length=20)),
                ('frame_material', models.CharField(max_length=20)),
                ('encapsulant_type', models.CharField(max_length=20)),
                ('encapsulant_manufacturer', models.CharField(max_length=20)),
                ('max_sys_volt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rated_isc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rated_voc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rated_imp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rated_vmp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rated_pmp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rated_ff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ManuFacturer')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCondition', models.CharField(max_length=100)),
                ('test_sequence', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('isc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vmp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pmp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noct', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='testlab',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='testresult',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestLab'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
        ),
    ]
