# Generated by Django 2.0.3 on 2018-04-15 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classdemov2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 7, 55, 1, 276450, tzinfo=utc)),
        ),
    ]
