# Generated by Django 2.0.3 on 2018-04-15 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classdemov2', '0002_auto_20180415_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 10, 54, 36, 186442, tzinfo=utc)),
        ),
    ]
